### ISSUE TITLE
所有api访问都报这个错

### ISSUE THREAD

**Issue by christan-duplicate** [JAVClub/core#26]
{"code":-1,"msg":"Access denied","data":{}}

登录返回也是这样的!

**Comment by christan-duplicate** [comment]
代理返回的是：
{
"code": -2,
"msg": "Access denied",
"data": {}
}

**Comment by isXiaoLin** [comment]
代理返回403为预期现象

请确认请求 core API 时是否携带有效 Cookie

christan-duplicate <notifications@github.com> 于 2020年8月8日周六 上午2:04写道：

**Comment by christan-duplicate** [comment]
输入帐号密码，f12查看，也是返回：{"code":-1,"msg":"Access denied","data":{}}

**Comment by christan-duplicate** [comment]
我调整了下反向代理，现在不报这个错了，便是登录成功跳转到首页后，瞬间又跳回到登录页了，也没提示什么错。

**Comment by christan-duplicate** [comment]
再登录一次就又可以了，
请问管理后台就只有一些简单的功能吗，那么想看看爬虫情况有后台吗？

**Comment by christan-duplicate** [comment]
现在首页显示 ： 
Files
2,600
其他变是0，这是什么意思呢？

**Comment by isXiaoLin** [comment]
没有爬虫的后台

仅有 Files 代表网盘中的内容不符合要求所以不进行导入，请检查 core 的相关日志

**Comment by christan-duplicate** [comment]
不知道为什么fetcher访问网站超时，但我已挂好梯子了
还有就是用 pm2 命令怎么写，NODE_ENV=dev 不生效哦。

**Comment by christan-duplicate** [comment]
[ERROR] Module: runAndSetInterval - [OneJAV: 0] Job threw an error FetchError: network timeout at: https://onejav.com/popular/
    at Timeout.<anonymous> (\fetcher\node_modules\node-fetch\lib\index.js:1448:13)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7) {
  type: 'request-timeout',
  attemptNumber: 6,
  retriesLeft: 0
}

**Comment by christan-duplicate** [comment]
原来用 node-fetch 是要手动配置代理的
安装：npm i https-proxy-agent
修改：\fetcher\src\pull\driver\onejav.js
添加：const HttpsProxyAgent = require('https-proxy-agent')
找到：timeout: 10000
替换成：
timeout: 10000,
agent: new HttpsProxyAgent("http://你的代理ip:端口")
------------------------------
修改：\fetcher\src\module\javbus.js
添加：const HttpsProxyAgent = require('https-proxy-agent')
找到：timeout: 7000
替换成：
timeout: 7000,
agent: new HttpsProxyAgent("http://你的代理ip:端口")
----------------------------------------

修改后重新运行就行了。

**Comment by christan-duplicate** [comment]
最新情况：queue.json
这个文件不停的增加，其它的什么都没反应，也没看到有下载种子文件.

**Comment by christan-duplicate** [comment]
[2020-08-09T22:25:03.022] [INFO] Module: runAndSetInterval - [Download queue] Starting job
[2020-08-09T22:25:03.026] [INFO] Module: runAndSetInterval - [Download queue] Job finished, setting timer
[2020-08-09T22:25:15.191] [INFO] Module: runAndSetInterval - [Check torrent status] Starting job
[2020-08-09T22:25:15.194] [INFO] Module: runAndSetInterval - [Check torrent status] Job finished, setting timer
[2020-08-09T22:25:32.652] [INFO] Module: runAndSetInterval - [OneJAV: 0] Starting job
[
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false },
  Node { namespace: null, text: undefined, _selfCloseTag: false }
]
[2020-08-09T22:25:35.352] [INFO] Module: runAndSetInterval - [OneJAV: 0] Job finished, setting timer
[2020-08-09T22:26:03.029] [INFO] Module: runAndSetInterval - [Download queue] Starting job
[2020-08-09T22:26:03.032] [INFO] Module: runAndSetInterval - [Download queue] Job finished, setting timer
[2020-08-09T22:26:15.207] [INFO] Module: runAndSetInterval - [Check torrent status] Starting job
[2020-08-09T22:26:15.210] [INFO] Module: runAndSetInterval - [Check torrent status] Job finished, setting timer


看日志，就是一直就这样循环。

**Comment by christan-duplicate** [comment]
qbittorrent也用上代理就可以正常下载了

**Comment by christan-duplicate** [comment]
现在就是：rclone move 监听此目录 不会操作了，请问有没有详细例子啊，如何监听？
还有就是 pm2 怎么才能让 NODE_ENV=dev 生效。
